#define PIN_SERIAL_TX PA_2
#define PIN_SERIAL_RX PA_3

#define PIN_I2C_SDA PB_7
#define PIN_I2C_SCL PB_6

#define PIN_CAN1_RXD PB_8
#define PIN_CAN1_TXD PB_9

#define PIN_HEART_LED1 PC_13
#define PIN_PCB_TEMP PA_0

#define PIN_PDOC_OK PB_15
#define PIN_DISCHARGE_RELAY PB_11

#define PIN_CAN1_RX_LED PB_1
#define PIN_CAN1_TX_LED PB_0