#include <mbed.h>

// CANBUS Frequency
#define CANBUS_FREQUENCY							500000

#define PRECHARGE_CONTROLLER_BASE_ID 0x440

typedef enum TS_STD_CAN_MESSAGES{
    TS_HEARTBEAT_ID,
    TS_ERROR_WARNING_ID,
    TS_DIGITAL_1_ID,
    TS_DIGITAL_2_ID,
    TS_ANALOGUE_1_ID,
    TS_ANALOGUE_2_ID,
} ts_std_can_messages_t;


// CANBUS Addresses
#define PRECHARGE_CONTROLLER_HEARTBEAT_ID 			0x440
#define PRECHARGE_CONTROLLER_ERROR_ID				0x441
#define PRECHARGE_CONTROLLER_ANALOGUE_ID			0x442
#define PRECHARGE_CONTROLLER_PERIPHERAL_ID			0x443

#define DISCHARGE_MODULE_HEARTBEAT_ID			 	0x450
#define DISCHARGE_MODULE_ERROR_ID					0x451
#define DISCHARGE_MODULE_ANALOGUE_ID				0x452
#define DISCHARGE_MODULE_PERIPHERAL_ID				0x453

// Throttle Controller
#define THROTTLE_CONTROLLER_HEARTBEAT_ID			0x340
#define THROTTLE_CONTROLLER_ERROR_ID				0x341
#define THROTTLE_CONTROLLER_ANALOGUE_ID				0x342
#define THROTTLE_CONTROLLER_PERIPERAL_ID			0x343

// Brake Module
// Orion BMS 2
#define ORION_BMS_STATUS_ID							0x180
#define ORION_BMS_VOLTAGE_ID						0x181
#define ORION_BMS_TEMPERATURE_ID					0x182

#define ORION_BMS_RINEHART_LIMITS					0x202
// Orion TEM
// Dash
// Motor Controllers

#define TC_CHARGER_STATUS_ID						0x18FF50E5